### PR TITLE
Fix issue with trying to parse "Not Scheduled" as timestamp

### PR DESCRIPTION
**Pull request by ChrisTheBaron**

### CODE REVIEW

**Comment by CaptainHayashi** [comment]
It feels as if there should be some sort of 'unscheduled' flag on the season that is set when this happens.  I suppose one could just test for the zero value on `FirstTime` (midnight 1st Jan 1970?), but this seems a bit unwieldy.

**Comment by ChrisTheBaron** [comment]
So there is the `IsZero` function to doing that kind of check. If it's documented that the "zero" value for `FirstTime` is that the season isn't scheduled, it should be fine, right?

**Comment by ChrisTheBaron** [comment]
Summons a @Brookke and @LordAro for their thoughts

**Comment by LordAro** [comment]
As long as it's nicely documented, I'm happy for a '0' timestamp to mean unscheduled

**Comment by Brookke** [comment]
Agreed although see https://github.com/UniversityRadioYork/myradio-go/issues/24

**Comment by LordAro** [comment]
Update from @ChrisTheBaron required

**Comment by ChrisTheBaron** [comment]
@LordAro what do I need to update here? :P

**Pull request merged**
